Relax CompileTimeConstant constraint on SafeArg/UnsafeArg name
palantir/safe-logging pull request #106
Opened 2019-01-19 17:35 UTC by cakofony

Revert "Annotate SafeArg/UnsafeArg name parameter with @CompileTimeConstant (#105)"

It's a relatively common use-case to provide dynamic names for SafeArg and UnsafeArg. Users have already classified the arg value as safe or unsafe so it is reasonable to assume they have properly considered the name as well.

2019-01-19 17:40 UTC, cakofony commented
I could go either way on this. In an ideal world I would prefer to require compile time constant names, but this would require changes to several projects. The constraint addition to Safe*Exception and Preconditions provide more utility than arg name validation.

2019-01-21 10:46 UTC, markelliot requested changes
I think we shouldn't be providing dynamic values to the arg names.

2019-01-21 12:22 UTC, cakofony commented
Great, if you're not worried about a bit of manual work to update existing codebases, I'm happy to close this out.

2019-01-21 12:22 UTC, closed without merging

2019-02-11 18:26 UTC, leonz commented
We have a use case where we are passing through metrics from another source, thus supplying dynamic values to the argument names.  We don't know what these names are at compile time, but do know that they are safe.

How would you recommend resolving the break introduced here?

2019-02-15 01:49 UTC, fmance commented
+1 We also have a very similar use case as described by @leonz