Support for lazy arguments
palantir/safe-logging pull request #14
Opened 2017-07-21 13:12 UTC by NeilRickards

What do you think to something like this?  Then, instead of:
```
    if (logger.isDebugEnabled()) {
        logger.debug("Message {}", SafeArg.of("name", expensiveFunc()));
    }
```
I could do:
```
    logger.debug("Message {}", SafeArg.of("name", () -> expensiveFunc()));
```
Log4j 2 supports something similar, but slf4j are still talking about it.

2017-07-21 15:58 UTC, markelliot commented
Might be preferable to do this in the `Appender`

2017-07-22 15:22 UTC, NeilRickards commented
How would that work @markelliot?  At the point I call `org.slf4j.Logger.debug` I don't know what the appender is, so don't know if a Supplier will be evaluated.  All I can be confident of is it will call `toString` on the object I pass.

2017-07-26 03:52 UTC, markelliot commented
I see; I suppose this is fine, then.

From: Neil Rickards <notifications@github.com>
Reply-To: palantir/safe-logging <reply@reply.github.com>
Date: Saturday, July 22, 2017 at 8:22 AM
To: palantir/safe-logging <safe-logging@noreply.github.com>
Cc: Mark Elliot <melliot@palantir.com>, Mention <mention@noreply.github.com>
Subject: Re: [palantir/safe-logging] Support for lazy arguments (#14)


How would that work @markelliot[github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_markelliot&d=DwMFaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=Vp81aOxWZvuVgVK_wp-VF3pIYG92B19LcCw6XKeYC0U&m=e71RxDfs6WKpG7m-iAD8JNgzc0m4TQR3E0ohi71B6AY&s=kIo37ytNHug0OFKRLS_HX6vG3fdcXlBOfMEpeo3km48&e=>? At the point I call org.slf4j.Logger.debug I don't know what the appender is, so don't know if a Supplier will be evaluated. All I can be confident of is it will call toString on the object I pass.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub[github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palantir_safe-2Dlogging_pull_14-23issuecomment-2D317190547&d=DwMFaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=Vp81aOxWZvuVgVK_wp-VF3pIYG92B19LcCw6XKeYC0U&m=e71RxDfs6WKpG7m-iAD8JNgzc0m4TQR3E0ohi71B6AY&s=Ds11hHnqAokbdVzpLGbkhatfW0OUhr0-wphawQk4MUQ&e=>, or mute the thread[github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAp3Q6uCjRdkTGyTURVkd36QFxtGB1rrks5sQhOxgaJpZM4OfYkm&d=DwMFaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=Vp81aOxWZvuVgVK_wp-VF3pIYG92B19LcCw6XKeYC0U&m=e71RxDfs6WKpG7m-iAD8JNgzc0m4TQR3E0ohi71B6AY&s=np2VPo6DWHpoyLPA4vPmM5SlEDC3MMSq01Q2mJtlhOE&e=>.

2017-07-28 05:39 UTC, gracew commented
our internal layout actually doesn't call `toString` on objects by default, preferring to use the json representation if one exists.

so I think we need to make this change to `getValue` as well.

also, I think this closes #8

2017-08-24 16:01 UTC, NeilRickards commented
Good point @gracew.  Updated -> how about something like this?

2017-08-24 22:44 UTC, schlosna reviewed
I have some perf concerns around current impl

2017-08-24 22:44 UTC, schlosna commented on safe-logging/src/main/java/com/palantir/logsafe/SafeArg.java
> +        return new SafeArg<>(name, () -> value);
Would highly recommend adding some JMH benchmarks to compare before and after here as this is going to add more allocations on potentially hot paths. I have a feeling we probably want a lazy and static impl for each safe and unsafe, and you can move most code into an abstract base class

2017-08-24 22:44 UTC, schlosna commented on safe-logging/src/main/java/com/palantir/logsafe/Arg.java
> +    private T value;
See below, but I don't think we want to eat these extra fields for non-lazy args

2018-10-26 15:19 UTC, cakofony commented
This code is entirely unnecessary if we use a better logging api, as mentioned in the description the following already works as you have described using log4j2 `org.apache.logging.log4j.Logger`:

```java
log.info("Hello {}", () -> SafeArg.of("whom", "World"));
```

This approach avoids the allocation of a new SafeArg insteace, only requiring a new supplier, where the proposed solution requires allocation of both.

2019-01-17 16:00 UTC, carterkozak requested changes
I don't think it's Args job to solve this.

2019-02-22 15:30 UTC, closed without merging